/*
# Create invite_codes table

1. New Tables
- `invite_codes` — codes generated by admins that students/sub-admins use to sign up.
  - code (text, unique) — the invite code string.
  - role (text) — the role this code grants ('student' or 'admin').
  - created_by (uuid) — the admin who created the code.
  - used_by (uuid, nullable) — the user who consumed the code.
  - used_at (timestamptz, nullable) — when it was consumed.
  - created_at (timestamptz).
2. Security
- RLS enabled.
- SELECT: authenticated can read (needed to validate code on signup).
- INSERT/UPDATE/DELETE: admin only.
*/

CREATE TABLE IF NOT EXISTS public.invite_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'student' CHECK (role IN ('student','admin')),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  used_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.invite_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "invite_codes_select_all" ON public.invite_codes;
CREATE POLICY "invite_codes_select_all"
ON public.invite_codes FOR SELECT
TO authenticated USING (true);

DROP POLICY IF EXISTS "invite_codes_admin_insert" ON public.invite_codes;
CREATE POLICY "invite_codes_admin_insert"
ON public.invite_codes FOR INSERT
TO authenticated WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "invite_codes_admin_update" ON public.invite_codes;
CREATE POLICY "invite_codes_admin_update"
ON public.invite_codes FOR UPDATE
TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "invite_codes_admin_delete" ON public.invite_codes;
CREATE POLICY "invite_codes_admin_delete"
ON public.invite_codes FOR DELETE
TO authenticated USING (public.is_admin());

CREATE INDEX IF NOT EXISTS idx_invite_codes_code ON public.invite_codes(code);
